import React from "react";

const timelineItems = [
  {
    title: "Step 1: AI-Generated Fingerprints",
    description:
      "The detector model is our main model to be implemented in our website such that it gives an accuracy of the given fingerprint. The accuracy is based on our training model from the datasets imported.",
    align: "left",
  },
  {
    title: "Step 2: Advanced AI Detection",
    description:
      "The ai generator model generates fingerprint such that the detector base could use the data generated by this model to train. It in turn trains from the detector model for training.",
    align: "right",
  },
  {
    title: "Step 3: Continuous Model Improvement",
    description:
      "With every detection, the AI system learns and adapts, improving its accuracy over time. It incorporates new data from real-world interactions, refining its ability to detect increasingly sophisticated spoofing techniques. The model undergoes continuous updates and retraining, ensuring it remains effective against the latest threats.",
    align: "left",
  },
];

const OurSoulution = () => {
  return (
    <section id="our-journey" className="py-16 px-8 text-center bg-black/90 font-body">
      <h2
        className="text-3xl md:text-4xl font-bold bg-clip-text text-transparent bg-gradient-to-r from-red-400 to-orange-500 font-logo"
        data-aos="fade-up"
        data-aos-duration="1000"
      >
        Our Solution
      </h2>

      <div className="relative max-w-4xl mx-auto mt-16">
        {/* Timeline Line (Centered) */}
        <div className="absolute top-0 left-1/2 w-[4px] h-full bg-gradient-to-b from-orange-500 to-red-500 transform -translate-x-1/2"></div>

        {/* Timeline Items */}
        <div className="flex flex-col space-y-16 relative">
          {timelineItems.map((item, index) => (
            <div
              key={index}
              className={`relative flex items-center ${
                item.align === "left" ? "justify-start" : "justify-end"
              }`}
              data-aos="fade-up"
              data-aos-duration="1000"
            >
              {/* Timeline Dot (Centered on Line) */}
              <div className="absolute left-1/2 w-6 h-6 bg-gradient-to-r from-[#FF5F6D] to-[#FFC371] border-4 border-black rounded-full transform -translate-x-1/2"></div>

              {/* Timeline Card */}
              <div
                className={`w-full md:w-[45%] p-6 bg-white/5 hover:bg-gray-800 border border-gray-700 shadow-lg rounded-xl text-left backdrop-blur-md ${
                  item.align === "right" ? "ml-auto" : "mr-auto"
                }`}
              >
                <h3 className="text-xl font-bold text-white font-logo">{item.title}</h3>
                <p className="text-gray-400 mt-2 font-body">{item.description}</p>
              </div>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
};

export default OurSoulution;
